apiVersion: v1
kind: ConfigMap
metadata: { name: fraud-pipeline-config }
data:
  SPRING_PROFILES_ACTIVE: docker
  DB_HOST: postgres.example.internal
  REDIS_HOST: redis.example.internal
  KAFKA_BOOTSTRAP_SERVERS: kafka.example.internal:9092
